# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: coffeemachine
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachine?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

build:
  version: "1.0"

account:
  message: "Bienvenue sur l'application Café PROD"
  details:
    name: "Bob Prod"
    email: "test@prod.fr"
    # email: '{cipher}196b1e6a9d721accc7f971246df5252d8f1f551b5ff80b4d5dd541c60df6aaa2'
  phone:
  - 0602530852
  - 09070605
  - 0820020222

# management:
# endpoints:
#     web:
#      exposure:
#         include: '*'
# logging:
#   level:
#     org:
#       formation:
#         controller:
#           CoffeeController: error
# greeting:
#   name: Dakota
#   coffee: ${greeting.name} is drinking Cafe Cereza
